In [2]:
from ucimlrepo import fetch_ucirepo 
  
# fetch dataset 
iris = fetch_ucirepo(id=53) 
  
# data (as pandas dataframes) 
X = iris.data.features 
y = iris.data.targets 
  
# metadata 
print(iris.metadata) 
  
# variable information 
print(iris.variables)

{'uci_id': 53, 'name': 'Iris', 'repository_url': 'https://archive.ics.uci.edu/dataset/53/iris', 'data_url': 'https://archive.ics.uci.edu/static/public/53/data.csv', 'abstract': 'A small classic dataset from Fisher, 1936. One of the earliest known datasets used for evaluating classification methods.\n', 'area': 'Biology', 'tasks': ['Classification'], 'characteristics': ['Tabular'], 'num_instances': 150, 'num_features': 4, 'feature_types': ['Real'], 'demographics': [], 'target_col': ['class'], 'index_col': None, 'has_missing_values': 'no', 'missing_values_symbol': None, 'year_of_dataset_creation': 1936, 'last_updated': 'Tue Sep 12 2023', 'dataset_doi': '10.24432/C56C76', 'creators': ['R. A. Fisher'], 'intro_paper': {'ID': 191, 'type': 'NATIVE', 'title': 'The Iris data set: In search of the source of virginica', 'authors': 'A. Unwin, K. Kleinman', 'venue': 'Significance, 2021', 'year': 2021, 'journal': 'Significance, 2021', 'DOI': '1740-9713.01589', 'URL': 'https://www.semanticscholar.org/paper/4599862ea877863669a6a8e63a3c707a787d5d7e', 'sha': None, 'corpus': None, 'arxiv': None, 'mag': None, 'acl': None, 'pmid': None, 'pmcid': None}, 'additional_info': {'summary': 'This is one of the earliest datasets used in the literature on classification methods and widely used in statistics and machine learning.  The data set contains 3 classes of 50 instances each, where each class refers to a type of iris plant.  One class is linearly separable from the other 2; the latter are not linearly separable from each other.\n\nPredicted attribute: class of iris plant.\n\nThis is an exceedingly simple domain.\n\nThis data differs from the data presented in Fishers article (identified by Steve Chadwick,  spchadwick@espeedaz.net ).  The 35th sample should be: 4.9,3.1,1.5,0.2,"Iris-setosa" where the error is in the fourth feature. The 38th sample: 4.9,3.6,1.4,0.1,"Iris-setosa" where the errors are in the second and third features.  ', 'purpose': 'N/A', 'funded_by': None, 'instances_represent': 'Each instance is a plant', 'recommended_data_splits': None, 'sensitive_data': None, 'preprocessing_description': None, 'variable_info': None, 'citation': None}}
           name     role         type demographic  \
0  sepal length  Feature   Continuous        None
1   sepal width  Feature   Continuous        None
2  petal length  Feature   Continuous        None
3   petal width  Feature   Continuous        None
4         class   Target  Categorical        None

                                         description units missing_values
0                                               None    cm             no
1                                               None    cm             no
2                                               None    cm             no
3                                               None    cm             no
4  class of iris plant: Iris Setosa, Iris Versico...  None             no

In [ ]:
'''
1° Passo - Matriz W
  Para cada linha, sortear 3 valores entre 0 e 1, cuja soma deles dá 1 (100%)
  Normalizar (??????????????????????????????????????????)
--> Teremos um peso para cada cluster (coluna --> 3 C1, C2, C3) para cada amostra (linha --> 150)

2° Passo - Calcular o centróide dos cluster
  Pra cada coluna (cluster)
    soma os valores da linha
    Aplica fórmula
    Peso_centroide_x = soma (vetor_linha * peso_linha --> vet*0.7) / som dos pesos (todas linhas)
          cj         =    ∑   xi        *   wij                   /    ∑   wij

    xi = [sepal length, sepal width, petal length, petal width]
    wij = somatória dos pesos
    cj = vetor com 4 entradas --> centroide pra cada variável     [c1, c2, c3, c4]

3° Passo - Atualizar pesos
  Pra cada linha
    Calcula o peso pra cada cluster
    wi1 = xxxxx <-- dist_euclidiana(Xi - c1) / dist_euclidiana(Xi - c1) + dist_euclidiana(Xi - c2) + dist_euclidiana(Xi - c3)
    wi2 = xxxxx
    wi3 = xxxxx


'''

In [3]:
# 1° Passo - Montar Matriz W com sorteio

import random
import pandas as pd
import numpy as np

# Amostra C1 C2 C3
W = []

# Teremos que fazer o sorteio de 3 valores 150 vezes (tamanho da iris)
for linha in range(len(X)):
    # Gerando 3 números aleatórios
    prob = [random.random() for _ in range(3)]

    # Transformando em entre 0 e 1 (percentual)
    prob_normalizados = [x / sum(prob) for x in prob]
    
    W.append(prob_normalizados)
    
W = pd.DataFrame(W, columns=['C1', 'C2', 'C3'])
W

           C1        C2        C3
0    0.198362  0.406401  0.395237
1    0.193557  0.493358  0.313084
2    0.529476  0.274414  0.196110
3    0.533322  0.019946  0.446732
4    0.411707  0.415200  0.173093
..        ...       ...       ...
145  0.046260  0.437075  0.516665
146  0.215307  0.747182  0.037511
147  0.618793  0.305095  0.076113
148  0.166232  0.649941  0.183826
149  0.535939  0.050096  0.413965

[150 rows x 3 columns]

In [ ]:
# 2° Passo - Calcular o centróide dos cluster

# Criando o campo xi com todos os dados direto no df
X['xi'] = list(X[['sepal length', 'sepal width', 'petal length', 'petal width']].values)


def calcular_centroides(X, W):
    centroides = []

    # Para cada coluna, calcularemos o centroide
    for col in W.columns:
        sum_xi_wij = sum(xi * peso for xi, peso in zip(X['xi'], W[col]))
        sum_wij = W[col].sum()
        
        centroides.append(sum_xi_wij / sum_wij)

    return centroides

In [7]:
# 3° Passo - Atualizar pesos

# Função de distância Euclidiana
def dist(a, b):
    return np.linalg.norm(a - b)

# Função para atualizar os pesos
def att_pesos(centroides, X):
    m = 2 
    novos_pesos = []
    # Pra cada linha, atualizaremos os pesos
    for _, linha in X.iterrows():
        # Extraindo a linha
        xi = linha['xi']
        
        # Calculando a distância de cada centroide para essa linha
        distancias = [dist(xi, c) for c in centroides]
        
        probabilidade_att = []
        for d in distancias:
            # Se a distância for 0, o peso é 1
            if d == 0:
                probabilidade_att.append(1.0)
            else:
                soma_razões = sum([(d / d_2)**(2/(m-1)) for d_2 in distancias])
                probabilidade_att.append(1 / soma_razões)
                
        novos_pesos.append(probabilidade_att)

    # Atualizando a matriz W com os novos pesos calculados
    W = pd.DataFrame(novos_pesos, columns=['C1', 'C2', 'C3'])
    return W

In [8]:
# Colocar isso em um loop
# Critério de parada?

for i in range(20):
   centroides = calcular_centroides(X, W)
   W = att_pesos(centroides, X)
   print(centroides, '\n')

[array([3.92453288, 1.27027111, 5.91647509, 3.04298472]), array([3.5733888 , 1.12909833, 5.78553696, 3.09446822]), array([3.78353566, 1.19879198, 5.82994805, 3.0236587 ])]

[array([4.00623203, 1.3002429 , 5.93980357, 3.02576887]), array([3.44057932, 1.0694426 , 5.72770357, 3.10048146]), array([3.77598327, 1.20460733, 5.84255521, 3.0427925 ])]

[array([4.13053581, 1.35107911, 5.98521034, 3.00828312]), array([3.23289798, 0.9834211 , 5.64835878, 3.12694378]), array([3.78949814, 1.21108516, 5.85006484, 3.04277124])]

[array([4.29538577, 1.42041243, 6.05084281, 2.99011638]), array([2.90925799, 0.84880943, 5.527545  , 3.17387345]), array([3.82726195, 1.22604172, 5.85854292, 3.029004  ])]

[array([4.50631606, 1.51141456, 6.14037252, 2.97157457]), array([2.48155386, 0.66994601, 5.37003618, 3.2407804 ]), array([3.93072085, 1.26539351, 5.87921165, 2.99123026])]

[array([4.75808443, 1.62314466, 6.25325112, 2.9549319 ]), array([2.07584686, 0.49924158, 5.22277028, 3.30738826]), array([4.14525787, 1.34627953, 5.92645659, 2.92191355])]

[array([4.98519661, 1.72984451, 6.36071791, 2.94658432]), array([1.83716054, 0.39830743, 5.13345998, 3.34311869]), array([4.37436339, 1.4284612 , 5.9863804 , 2.86003544])]

[array([5.11375715, 1.79575888, 6.42591098, 2.94881982]), array([1.75251176, 0.36223756, 5.09707896, 3.35011169]), array([4.48298987, 1.46458045, 6.02456259, 2.84054015])]

[array([5.16861781, 1.82384051, 6.45729654, 2.9555098 ]), array([1.73238225, 0.35346688, 5.08593795, 3.34888578]), array([4.51146488, 1.47471198, 6.03565642, 2.83514576])]

[array([5.19244283, 1.83575849, 6.47268619, 2.96044358]), array([1.72743539, 0.35126929, 5.08262623, 3.34792338]), array([4.51324009, 1.47498007, 6.03462201, 2.83224497])]

[array([5.20455934, 1.84174551, 6.48102109, 2.96330313]), array([1.72514212, 0.35028469, 5.0813778 , 3.34782118]), array([4.5085882 , 1.47260664, 6.03064854, 2.83018504])]

[array([5.21176278, 1.84527431, 6.48604619, 2.96498581]), array([1.72348302, 0.34959806, 5.08073842, 3.3480625 ]), array([4.50352307, 1.47011372, 6.02683217, 2.82866695])]

[array([5.21644826, 1.84755533, 6.48930446, 2.96604416]), array([1.7222251 , 0.34908537, 5.08034241, 3.34835223]), array([4.49945527, 1.4681243 , 6.02385881, 2.82756587])]

[array([5.21961105, 1.8490887 , 6.49149449, 2.9667429 ]), array([1.72130533, 0.34871261, 5.08007811, 3.34859476]), array([4.49647758, 1.46667151, 6.02170313, 2.82678366])]

[array([5.22177081, 1.85013294, 6.49298671, 2.96721505]), array([1.72065276, 0.34844871, 5.07989781, 3.34877572]), array([4.49437754, 1.46564851, 6.02018727, 2.8262366 ])]

[array([5.22324842, 1.85084607, 6.49400693, 2.96753671]), array([1.72019806, 0.34826499, 5.07977433, 3.3489045 ]), array([4.49292164, 1.46494013, 6.01913695, 2.82585798])]

[array([5.2242582 , 1.85133281, 6.49470417, 2.96775623]), array([1.71988447, 0.34813834, 5.07968984, 3.34899418]), array([4.49192104, 1.46445374, 6.01841492, 2.8255977 ])]

[array([5.22494712, 1.8516646 , 6.49517997, 2.96790593]), array([1.7196695 , 0.34805153, 5.07963215, 3.34905596]), array([4.49123667, 1.4641213 , 6.01792087, 2.82541955])]

[array([5.22541642, 1.85189048, 6.49550419, 2.96800792]), array([1.71952266, 0.34799225, 5.07959283, 3.34909826]), array([4.4907699 , 1.46389467, 6.01758377, 2.82529796])]

[array([5.22573573, 1.85204411, 6.49572485, 2.96807733]), array([1.71942259, 0.34795184, 5.07956606, 3.34912714]), array([4.49045211, 1.46374044, 6.01735419, 2.82521513])]

In [ ]:
# Pendências:
# Como escolhe o m??
# Normalizar? Isso é no sorteio?  <-- confirmar


# Pensar e implementar um critério de parada
# Classificar classe pra cada amostras 
# Plotar
# Talvez fazer um comparativo com os dados reais

# Duvida do passo 3:
# Pega a db, filtra pra virgínica e versicolor e roda tudo dnv só que com 2 clusters?
# o que é demonstrar a pertinência intermediária?

# É necessário tornar o código universal? Tipo fazer uma biblioteca?

In [9]:
W

           C1        C2        C3
0    0.007364  0.981040  0.011596
1    0.013474  0.964936  0.021591
2    0.016288  0.958156  0.025555
3    0.017109  0.955486  0.027405
4    0.009425  0.975828  0.014747
..        ...       ...       ...
145  0.864529  0.011300  0.124171
146  0.662711  0.013385  0.323904
147  0.976792  0.001357  0.021852
148  0.772618  0.020962  0.206420
149  0.576700  0.015067  0.408233

[150 rows x 3 columns]